#############################################################################
# Makefile for building: quetalk
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  quetalk.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile quetalk.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-lib \
		sub-app


sub-lib-qmake_all:  FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile
	cd lib/ && $(MAKE) -f Makefile qmake_all
sub-lib: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile
sub-lib-make_first-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-lib-make_first: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-lib-all-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-lib-all: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-lib-clean-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-lib-clean: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-lib-distclean-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-lib-distclean: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-lib-install_subtargets-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-lib-install_subtargets: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-lib-uninstall_subtargets-ordered: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-lib-uninstall_subtargets: FORCE
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-qmake_all: sub-lib-qmake_all FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile
	cd app/ && $(MAKE) -f Makefile qmake_all
sub-app: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile
sub-app-make_first-ordered: sub-lib-make_first-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-make_first: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-app-all-ordered: sub-lib-all-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-all: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-app-clean-ordered: sub-lib-clean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-clean: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-app-distclean-ordered: sub-lib-distclean-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-distclean: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-app-install_subtargets-ordered: sub-lib-install_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-install_subtargets: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-app-uninstall_subtargets-ordered: sub-lib-uninstall_subtargets-ordered  FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-app-uninstall_subtargets: FORCE
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: quetalk.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		quetalk.pro
	$(QMAKE) -o Makefile quetalk.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
quetalk.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile quetalk.pro

qmake_all: sub-lib-qmake_all sub-app-qmake_all FORCE

make_first: sub-lib-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-lib-all-ordered sub-app-all-ordered FORCE
clean: sub-lib-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-lib-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-lib-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-lib-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

sub-lib-check_ordered:
	@test -d lib/ || mkdir -p lib/
	cd lib/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/lib/lib.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-app-check_ordered: sub-lib-check_ordered 
	@test -d app/ || mkdir -p app/
	cd app/ && ( test -e Makefile || $(QMAKE) /home/prointegra/Documentos/desarrollo/respositorios_git_dev/QueTalk/app/app.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-lib-check_ordered sub-app-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

